development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:e805799b960102ec5c25f629b8eb433c@hammerjaw.redistogo.com:9529/
  channel_prefix: ruby_music_01_production
